apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devsecops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
